name: Check for update
on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Owner of the component"
        required: true
        type: string
        default: "emukidid"
      component:
        description: "Repository of the component"
        required: true
        type: string
        default: "swiss-gc"

jobs:
  check-for-update:
    name: Check for update
    runs-on: ubuntu-latest
    outputs:
      RELEASE: ${{ steps.check-for-update.outputs.RELEASE }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            build/releases
      - id: swiss
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ${{ github.event.inputs.owner }}
          repo: ${{ github.event.inputs.component }}
          excludes: prerelease, draft
      - id: check-for-update
        run: |
          NEW="https://github.com/${{ github.event.inputs.owner }}/${{ github.event.inputs.component }}/releases/tag/${{steps.swiss.outputs.release}}"
          CURRENT=$(cat build/releases/swiss-release.txt)
          
          if [[ "" != "$NEW" && "$NEW" != "$CURRENT" ]]; then
            echo "New ${{ github.event.inputs.owner }}/${{ github.event.inputs.component }} release available: ${{steps.swiss.outputs.release}}"
            echo $NEW > build/releases/swiss-release.txt
            echo "RELEASE=$NEW" >> $GITHUB_OUTPUT
          fi
  update-component:
    name: Update component
    runs-on: ubuntu-latest
    needs: check-for-update
    if: ${{ needs.check-for-update.outputs.RELEASE != '' }}
    steps:
      - uses: actions/checkout@v4
      - id: update-component
        # https://github.com/emukidid/swiss-gc/releases/tag/v0.6r1788
        # https://github.com/emukidid/swiss-gc/releases/download/v0.6r1788/swiss_r1788.7z
        run: |
          echo "${{needs.check-for-update.outputs.RELEASE}}" > build/releases/swiss-release.txt
          ARCHIVE=$(echo "${{needs.check-for-update.outputs.RELEASE}}" | sed 's/\/tag\//\/download\//' | sed 's/(\/v[0-9.]+(r[0-9]+))$/$1\/swiss_$2.7z/')
          mkdir tmp
          curl ${{needs.check-for-update.outputs.RELEASE}} -o tmp/component.zip
          git add build/releases/swiss-release.txt tmp/component.zip
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7