name: Check for update
on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Owner of the component"
        required: true
        type: string
        default: "emukidid"
      component:
        description: "Repository of the component"
        required: true
        type: string
        default: "swiss-gc"

jobs:
  build:
    name: Check for update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            build/releases
      - id: swiss
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ${{ github.event.inputs.owner }}
          repo: ${{ github.event.inputs.component }}
          excludes: prerelease, draft
      - id: check-for-update
        run: |
          NEW="https://github.com/${{ github.event.inputs.owner }}/${{ github.event.inputs.component }}/releases/tag/${{steps.swiss.outputs.release}}"
          CURRENT=$(cat build/releases/swiss-release.txt)
          
          if [[ "" != "$NEW" && "$NEW" != "$CURRENT" ]]; then
            echo "New ${{ github.event.inputs.owner }}/${{ github.event.inputs.component }} release available: ${{steps.swiss.outputs.release}}"
          fi
#      - id: gbi
#        description: "Get latest release of GameBoy Interface"
#        uses: pozetroninc/github-action-get-latest-release@master
#        with:
#          owner: extremscorner
#          repo: emgba
#          excludes: prerelease, draft
#      - id: cleanrip
#        description: "Get latest release of Cleanrip"
#        uses: pozetroninc/github-action-get-latest-release@master
#        with:
#          owner: emukidid
#          repo: cleanrip
#          excludes: prerelease, draft
#      - id: gcmm
#        description: "Get latest release of GameCube Memory Manager"
#        uses: pozetroninc/github-action-get-latest-release@master
#        with:
#          owner: suloku
#          repo: gcmm
#          excludes: prerelease, draft